fixess

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,9 +1,10 @@
-name: Deploy FunzyCode
+name: Deploy FunzyCode App
 
 on:
   push:
     branches:
       - main
+  workflow_dispatch:
 
 jobs:
   deploy:
@@ -17,19 +18,31 @@ jobs:
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
+            set -e
+
+            echo "Going to project folder..."
             cd /home/ubuntu/funzycodeapp
 
             echo "Pulling latest code..."
             git pull origin main
 
+            echo "Checking .env file..."
+            if [ ! -f .env ]; then
+              echo ".env file missing in /home/ubuntu/funzycodeapp"
+              exit 1
+            fi
+
             echo "Stopping containers..."
             docker compose down
 
-            echo "Building new containers..."
+            echo "Building containers..."
             docker compose build --no-cache
 
             echo "Starting containers..."
             docker compose up -d
+
+            echo "Checking running containers..."
+            docker ps
 
             echo "Removing unused images..."
             docker image prune -af
